-- ProjNav VHDL simulation template: tbw_PIC24_testOV.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
